### ISSUE TITLE
Add crowd-sourcing of rulesets

### ISSUE THREAD

**Issue by sbarre** [psecio/iniscan#6]
Consider creating a website or other such interface to allow user submissions of rulesets for inclusion in the scanner, and then crowd-source their validity or correctness (via voting or other such mechanism).

**Comment by enygma** [comment]
Circling back around on this and thinking more about the rules, I'm not sure they change quite enough to need an external source. I could see some groups wanting to have custom checks, but that may not be something that would matter to other groups. @sbarre, thoughts?

**Comment by enygma** [comment]
Closing this issue out as it's pretty stale and no additional input was given. While I like the idea, I think it adds extra infrastructure worries that might be out of scope.
