### ISSUE TITLE
The configuration file could not be found

### ISSUE THREAD

**Issue by awebdeveloper** [psecio/iniscan#80]
I tried the following and it gives me the below error 

curl -LSs http://box-project.org/installer.php | php
php box.phar build

                                              
  [RuntimeException]                          
  The configuration file could not be found.  
                                              

build [-c|--configuration="..."]

I also tried the following but looks like configuration is some kind of json file 
php box.phar build --configuration="/etc/php5/cli/php.ini"

**Comment by enygma** [comment]
This sounds like the Box build handling can't find a configuration file, not that the scanner can't run. Is this correct?

**Comment by awebdeveloper** [comment]
I am still in the build process and not scan

**Comment by enygma** [comment]
Hmm, interesting....and you're doing this from the root of the iniscan clone? I just tried it and it cooperated fine here.

**Comment by danmbox** [comment]
Same here...
> $ cd ~/src/iniscan
> $ composer.phar require psecio/iniscan
> $ curl -LSs http://box-project.org/installer.php | php
> $ php box.phar build
>
>  [RuntimeException]                          
>  The configuration file could not be found.  
>                                              
>
>
> build [-c|--configuration="..."]

**Comment by denji** [comment]
$ cd ~/src/iniscan
$ composer.phar require psecio/iniscan
$ curl -LSs http://box-project.org/installer.php | php
$ php composer.phar  install
$ php box.phar build

**Comment by danmbox** [comment]
Aha. With `git clone`, and ALSO `php -d phar.readonly=0 box.phar`, yes, it works. With `composer.phar require psecio/iniscan`, it doesn't. Perhaps the author should post full, correct instructions for `box`-ing `iniscan`.

**Comment by fabarea** [comment]
:+1: encountered the same behaviour as described on the original post. Cloning the repository solved the problem.

**Comment by enygma** [comment]
Is everyone okay with closing this one out?

**Comment by enygma** [comment]
No response from other folks on the thread, assuming it's good. Closing.
