### ISSUE TITLE
Problem installing on PHP 7 (ocramius/instantiator dependency)

### ISSUE THREAD

**Issue by wasilak** [psecio/iniscan#95]
Hi,

There is problem when installing using composer ``global``, 
> - ocramius/instantiator 1.1.2 requires php ~5.3 -> your PHP version (7.0.3) or "config.platform.php" value does not satisfy that requirement.

because of out of date dependency ``ocramius/instantiator``, which is apparently abandoned:

> This package is abandoned and no longer maintained. The author suggests using the doctrine/instantiator package instead. 

BR,
Peter

**Comment by enygma** [comment]
@wasilak would updating the symfony/console version fix that? I think that'd be the only place this issue would come from.

**Comment by wasilak** [comment]
Hi @enygma,

Yes, it seams so. I cloned this repo locally, removed ``composer.lock`` and changed symfony/console to most recent (``3.0.2``) and after firing ``composer install`` everything went smoothly and ``doctrine/instantiator`` was installed instead of ``ocramius/instantiator``:
> Installing doctrine/instantiator (1.0.5)

Now I can run i.e. ``bin/iniscan show``. Hope it helps :)

BR,
Peter

**Comment by enygma** [comment]
@wasilak excellent - mind making a PR with that change in it? I'll get it merged ASAP :)

**Comment by enygma** [comment]
As #96 was merged resolving this I'm going to close this out if it's okay by you @wasilak

**Comment by enygma** [comment]
Closing this issue - no feedback but the issue seems resolved.
