### ISSUE TITLE
dump of the running php deamon

### ISSUE THREAD

**Issue by denji** [psecio/iniscan#97]
We can make dump active process as an alternative to the output from `php.ini`, any suggestions?

If there's more than one php file settings `stdout`:

``` bash
# curl site.com/phpinfo-api.json | ./vendor/bin/iniscan scan --format=json
$ php -r 'print(json_encode(ini_get_all(null, false), JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_BIGINT_AS_STRING));'
$ php -r 'var_export(ini_get_all(null, false));'
```

**Comment by enygma** [comment]
By "dump active process" I assume you're meaning the results from the `phpinfo()` page here? It's a bit hard to tell from your examples.
